name: docker-action
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  build-test-upload:
    runs-on: ubuntu-latest
    steps:
      - run: docker build -t yolo-my-apache . 
