name: docker-action
run-name: Running CI
on: [push]
jobs:
  build-test-upload:
    runs-on: ubuntu-latest
    steps:
      - name: "Building env. by importing the whole repo"
        uses: actions/checkout@v3
      - name: Building Docker image
        run: docker build -t dockeratelier:latest . 
      - name: "Testing built Docker image"
        run: |
          docker run --rm --name dockeratelier dockeratelier:latest
          exitcode=$?
          if [[ $exitcode -ne 0 ]]; then
            echo "ERREUR"
          fi
          exit $exitcode
      -
        name: Logging in Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      -
        name: Setting up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_LOGIN }}/dockeratelier:latest 

