name: docker-action
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  build-test-upload:
    runs-on: ubuntu-latest
    steps:
      - run: |
          cd /
          docker build -t dockeratelier . 
