name: docker-action
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  build-test-upload:
    runs-on: ubuntu-latest
    steps:
      - name: "[CI] Build l'environnement en récupérant le repo entier de votre branche."
        uses: actions/checkout@v3 
      - run: docker build -t dockeratelier:latest . 
      - name: "[DEBUG] Test de l'image docker"
        run: |
          exitcode=$? docker run --rm --name dockeratelier dockeratelier:latest
          if [ $exitcode -ne 0 ]; then
          echo "ERREUR"
          fi
          exit $exitcode
